struct GameOptionManager_vtables
{
    void (__thiscall* Function1)(struct GameOptionManager* this);
    void (__thiscall* Function2)(struct GameOptionManager* this);
    void (__thiscall* Function3)(struct GameOptionManager* this);
    void (__thiscall* Function4)(struct GameOptionManager* this);
    void (__thiscall* Function5)(struct GameOptionManager* this);
    void (__thiscall* Function6)(struct GameOptionManager* this);
    void (__thiscall* Function7)(struct GameOptionManager* this);
    void (__thiscall* Function8)(struct GameOptionManager* this);
    void (__thiscall* Function9)(struct GameOptionManager* this);
    void (__thiscall* Function10)(struct GameOptionManager* this);
    void (__thiscall* Function11)(struct GameOptionManager* this);
    void (__thiscall* Function12)(struct GameOptionManager* this);
    void (__thiscall* Function13)(struct GameOptionManager* this);
    void (__thiscall* Function14)(struct GameOptionManager* this);
    void (__thiscall* Function15)(struct GameOptionManager* this);
    void (__thiscall* Function16)(struct GameOptionManager* this);
    void (__thiscall* Function17)(struct GameOptionManager* this);
    void (__thiscall* Function18)(struct GameOptionManager* this);
    void (__thiscall* Function19)(struct GameOptionManager* this);
    void (__thiscall* Function20)(struct GameOptionManager* this);
    void (__thiscall* Function21)(struct GameOptionManager* this);
    void (__thiscall* Function22)(struct GameOptionManager* this);
    void (__thiscall* Function23)(struct GameOptionManager* this);
    void (__thiscall* Function24)(struct GameOptionManager* this);
    void (__thiscall* Function25)(struct GameOptionManager* this);
    void (__thiscall* Function26)(struct GameOptionManager* this);
    void (__thiscall* Function27)(struct GameOptionManager* this);
    void (__thiscall* Function28)(struct GameOptionManager* this);
    void (__thiscall* Function29)(struct GameOptionManager* this);
    int  (__thiscall* Function30)(struct GameOptionManager* this);
    void (__thiscall* Function31)(struct GameOptionManager* this);
    void (__thiscall* Function32)(struct GameOptionManager* this);
    void (__thiscall* Function33)(struct GameOptionManager* this);
    void (__thiscall* Function34)(struct GameOptionManager* this);
    void (__thiscall* Function35)(struct GameOptionManager* this);
    void (__thiscall* Function36)(struct GameOptionManager* this);
    void (__thiscall* Function37)(struct GameOptionManager* this);
    void (__thiscall* Function38)(struct GameOptionManager* this);
    void (__thiscall* Function39)(struct GameOptionManager* this);
    void (__thiscall* Function40)(struct GameOptionManager* this);
    void (__thiscall* Function41)(struct GameOptionManager* this);
    void (__thiscall* Function42)(struct GameOptionManager* this);
    void (__thiscall* Function43)(struct GameOptionManager* this);
    void (__thiscall* Function44)(struct GameOptionManager* this);
    void (__thiscall* Function45)(struct GameOptionManager* this);
    void (__thiscall* Function46)(struct GameOptionManager* this);
    void (__thiscall* Function47)(struct GameOptionManager* this);
    void (__thiscall* Function48)(struct GameOptionManager* this);
    void (__thiscall* Function49)(struct GameOptionManager* this);
    void (__thiscall* Function50)(struct GameOptionManager* this);
    void (__thiscall* Function51)(struct GameOptionManager* this);
    void (__thiscall* Function52)(struct GameOptionManager* this);
    void (__thiscall* Function53)(struct GameOptionManager* this);
    void (__thiscall* Function54)(struct GameOptionManager* this);
    void (__thiscall* Function55)(struct GameOptionManager* this);
    void (__thiscall* Function56)(struct GameOptionManager* this);
    void (__thiscall* Function57)(struct GameOptionManager* this);
    void (__thiscall* Function58)(struct GameOptionManager* this);
    void (__thiscall* Function59)(struct GameOptionManager* this);
    void (__thiscall* Function60)(struct GameOptionManager* this);
    void (__thiscall* Function61)(struct GameOptionManager* this);
    void (__thiscall* Function62)(struct GameOptionManager* this);
    void (__thiscall* Function63)(struct GameOptionManager* this);
    void (__thiscall* Function64)(struct GameOptionManager* this);
    void (__thiscall* Function65)(struct GameOptionManager* this);
    void (__thiscall* Function66)(struct GameOptionManager* this);
    int  (__thiscall* Function67)(struct GameOptionManager* this);
    void (__thiscall* Function68)(struct GameOptionManager* this);
    void (__thiscall* Function69)(struct GameOptionManager* this);
    void (__thiscall* Function70)(struct GameOptionManager* this);
    int  (__thiscall* GetWeaponRestriction)(struct GameOptionManager* this);
    void (__thiscall* Function72)(struct GameOptionManager* this);
    void (__thiscall* Function73)(struct GameOptionManager* this);
    void (__thiscall* Function74)(struct GameOptionManager* this);
    void (__thiscall* Function75)(struct GameOptionManager* this);
    void (__thiscall* Function76)(struct GameOptionManager* this);
    void (__thiscall* Function77)(struct GameOptionManager* this);
    void (__thiscall* Function78)(struct GameOptionManager* this);
    void (__thiscall* Function79)(struct GameOptionManager* this);
    void (__thiscall* Function80)(struct GameOptionManager* this);
    void (__thiscall* Function81)(struct GameOptionManager* this);
    void (__thiscall* Function82)(struct GameOptionManager* this);
    void (__thiscall* Function83)(struct GameOptionManager* this);
    void (__thiscall* Function84)(struct GameOptionManager* this);
    void (__thiscall* Function85)(struct GameOptionManager* this);
    void (__thiscall* Function86)(struct GameOptionManager* this);
    void (__thiscall* Function87)(struct GameOptionManager* this);
    void (__thiscall* Function88)(struct GameOptionManager* this);
    void (__thiscall* Function89)(struct GameOptionManager* this);
    void (__thiscall* Function90)(struct GameOptionManager* this);
    void (__thiscall* Function91)(struct GameOptionManager* this);
    int  (__thiscall* GetGameMode)(struct GameOptionManager* this);
    void (__thiscall* Function93)(struct GameOptionManager* this);
    void (__thiscall* Function94)(struct GameOptionManager* this);
    void (__thiscall* Function95)(struct GameOptionManager* this);
    void (__thiscall* Function96)(struct GameOptionManager* this);
    void (__thiscall* Function97)(struct GameOptionManager* this);
    void (__thiscall* Function98)(struct GameOptionManager* this);
    void (__thiscall* Function99)(struct GameOptionManager* this);
    void (__thiscall* Function100)(struct GameOptionManager* this);
    void (__thiscall* Function101)(struct GameOptionManager* this);
    void (__thiscall* Function102)(struct GameOptionManager* this);
    void (__thiscall* Function103)(struct GameOptionManager* this);
    void (__thiscall* Function104)(struct GameOptionManager* this);
    void (__thiscall* Function105)(struct GameOptionManager* this);
    void (__thiscall* Function106)(struct GameOptionManager* this);
    void (__thiscall* Function107)(struct GameOptionManager* this);
    void (__thiscall* Function108)(struct GameOptionManager* this);
    void (__thiscall* Function109)(struct GameOptionManager* this);
    void (__thiscall* Function110)(struct GameOptionManager* this);
    void (__thiscall* Function111)(struct GameOptionManager* this);
    void (__thiscall* Function112)(struct GameOptionManager* this);
    void (__thiscall* Function113)(struct GameOptionManager* this);
    void (__thiscall* Function114)(struct GameOptionManager* this);
    void (__thiscall* Function115)(struct GameOptionManager* this);
    void (__thiscall* Function116)(struct GameOptionManager* this);
    void (__thiscall* Function117)(struct GameOptionManager* this);
    void (__thiscall* Function118)(struct GameOptionManager* this);
    void (__thiscall* Function119)(struct GameOptionManager* this);
    void (__thiscall* Function120)(struct GameOptionManager* this);
    void (__thiscall* Function121)(struct GameOptionManager* this);
    void (__thiscall* Function122)(struct GameOptionManager* this);
    void (__thiscall* Function123)(struct GameOptionManager* this);
    void (__thiscall* Function124)(struct GameOptionManager* this);
    void (__thiscall* Function125)(struct GameOptionManager* this);
    void (__thiscall* Function126)(struct GameOptionManager* this);
    void (__thiscall* Function127)(struct GameOptionManager* this);
    void (__thiscall* Function128)(struct GameOptionManager* this);
    void (__thiscall* Function129)(struct GameOptionManager* this);
    void (__thiscall* Function130)(struct GameOptionManager* this);
    void (__thiscall* Function131)(struct GameOptionManager* this);
    void (__thiscall* Function132)(struct GameOptionManager* this);
    void (__thiscall* Function133)(struct GameOptionManager* this);
    void (__thiscall* Function134)(struct GameOptionManager* this);
    void (__thiscall* Function135)(struct GameOptionManager* this);
    void (__thiscall* Function136)(struct GameOptionManager* this);
    void (__thiscall* Function137)(struct GameOptionManager* this);
    void (__thiscall* Function138)(struct GameOptionManager* this);
    void (__thiscall* Function139)(struct GameOptionManager* this);
    void (__thiscall* Function140)(struct GameOptionManager* this);
    void (__thiscall* Function141)(struct GameOptionManager* this);
    void (__thiscall* Function142)(struct GameOptionManager* this);
    void (__thiscall* Function143)(struct GameOptionManager* this);
    void (__thiscall* Function144)(struct GameOptionManager* this);
    void (__thiscall* Function145)(struct GameOptionManager* this);
    void (__thiscall* Function146)(struct GameOptionManager* this);
    void (__thiscall* Function147)(struct GameOptionManager* this);
    void (__thiscall* Function148)(struct GameOptionManager* this);
    void (__thiscall* Function149)(struct GameOptionManager* this);
    void (__thiscall* Function150)(struct GameOptionManager* this);
    void (__thiscall* Function151)(struct GameOptionManager* this);
    void (__thiscall* Function152)(struct GameOptionManager* this);
    void (__thiscall* Function153)(struct GameOptionManager* this);
    void (__thiscall* Function154)(struct GameOptionManager* this);
    void (__thiscall* Function155)(struct GameOptionManager* this);
    void (__thiscall* Function156)(struct GameOptionManager* this);
    void (__thiscall* Function157)(struct GameOptionManager* this);
    void (__thiscall* Function158)(struct GameOptionManager* this);
    void (__thiscall* Function159)(struct GameOptionManager* this);
    unsigned char (__thiscall* ReturnUnk16)(struct GameOptionManager* this);
    void (__thiscall* Function161)(struct GameOptionManager* this);
    void (__thiscall* Function162)(struct GameOptionManager* this);
    void (__thiscall* Function163)(struct GameOptionManager* this);
    void (__thiscall* Function164)(struct GameOptionManager* this);
    void (__thiscall* Function165)(struct GameOptionManager* this);
    void (__thiscall* Function166)(struct GameOptionManager* this);
    void (__thiscall* Function167)(struct GameOptionManager* this);
    void (__thiscall* Function168)(struct GameOptionManager* this);
    void (__thiscall* Function169)(struct GameOptionManager* this);
    void (__thiscall* Function170)(struct GameOptionManager* this);
    void (__thiscall* Function171)(struct GameOptionManager* this);
    void (__thiscall* Function172)(struct GameOptionManager* this);
};

struct GameOptionManagerUnk1
{
	int unk1;
	int unk2;
	short unk3;
	int unk4;
	int unk5;
	int unk6;
	int unk7;
	int unk8;
	int unk9;
	int unk10;

	char unk21;
	int unk22;
	short unk23;
	int unk24;
	int unk25;
	int unk26;
	int unk27;
	int unk28;
	short unk29;
	int unk30;
    
	int unk31;
	int unk32;
	int unk33;
	int unk34;
	int unk35;
	int unk36;
	int unk37;
	int unk38;
	int unk39;
	int unk40;

	int unk41;
	char unk42;
	int unk43;
	short unk44;
	int unk45;
	int unk46;
	int unk47;
	int unk48;
	int unk49;
	int unk50;
    
	int unk51;
	short unk52;
	int unk53;
	int unk54;
	int unk55;
	int unk56;
	char unk57;
	int unk58;
	int unk59;
	int unk60;

	int unk61;
	int unk62;
	int unk63;
	int unk64;
	char unk65;
	int unk66;
	int unk67;
	int unk68;
	int unk69;
	int unk70;

	short unk71;
	int unk72;
	int unk73;
	int unk74;
	int unk75;
	int unk76;
	short unk77;
	int unk78;
	int unk79;
	int unk80;

	int unk81;
	int unk82;
	short unk83;
	int unk84;
	int unk85;
	int unk86;
	int unk87;
	int unk88;
	short unk89;
	int unk90;

	int unk91;
	int unk92;
	int unk93;
	int unk94;
	short unk95;
	int unk96;
	int unk97;
	int unk98;
	int unk99;
	int unk100;
    
    int unk101;
    int unk102;
    int unk103;
};

struct GameOptionManager
{
    GameOptionManager_vtables* vfptr;
    int unk1;
    GameOptionManagerUnk1 unk2;
    int unk3;
    int unk4;
    int unk5;
    int unk6;
    int unk7;
    struct CRoomSettingPart settings;
    int unk9;
    int unk10;
    int unk11;
    int unk12;
    int unk13;
    int unk14;
    int unk15;
    int unk16;
    int unk17;
    int unk18;
    int unk19;
    int unk20;
    int unk21;
};

struct MainGameOptionManager {
    void* vfptr;
    int nf1;
    int* nf2; // a4
    int* nf3; // a2
    int* nf4; // a3
    int nf5;
    int nf6;
    int nf7;
};

struct Packet_Option
{
    void* vfptr;
    struct CPacketBase base;
    int type;
    int unk1;
    int configSize;
    char config[0x2800]; // 10240
    int unk4; // option 1
};
